services:

  testrunner:
    image: $DEV_IMAGE_TAG
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        OTP_VERSION: $OTP_VERSION
        THRIFT_VERSION: $THRIFT_VERSION
    volumes:
      - .:$PWD
    hostname: fistful-server
    depends_on:
      machinegun:
        condition: service_healthy
      dominant:
        condition: service_healthy
      party-management:
        condition: service_healthy
      limiter:
        condition: service_healthy
      shumway:
        condition: service_healthy
      bender:
        condition: service_healthy
    working_dir: $PWD
    command: /sbin/init

  dominant:
    image: ghcr.io/valitydev/dominant:sha-fdf5277
    command: /opt/dominant/bin/dominant foreground
    depends_on:
      machinegun:
        condition: service_healthy
    healthcheck:
      test: "/opt/dominant/bin/dominant ping"
      interval: 10s
      timeout: 5s
      retries: 10

  machinegun:
    image: ghcr.io/valitydev/machinegun:sha-ed72eec
    command: /opt/machinegun/bin/machinegun foreground
    volumes:
      - ./test/machinegun/config.yaml:/opt/machinegun/etc/config.yaml
      - ./test/machinegun/cookie:/opt/machinegun/etc/cookie
    healthcheck:
      test: "/opt/machinegun/bin/machinegun ping"
      interval: 10s
      timeout: 5s
      retries: 10

  limiter:
    image: ghcr.io/valitydev/limiter:sha-6c3bfe3
    command: /opt/limiter/bin/limiter foreground
    depends_on:
      machinegun:
        condition: service_healthy
      shumway:
        condition: service_healthy
    healthcheck:
      test: "/opt/limiter/bin/limiter ping"
      interval: 5s
      timeout: 1s
      retries: 20

  shumway:
    image: docker.io/rbkmoney/shumway:44eb989065b27be619acd16b12ebdb2288b46c36
    restart: unless-stopped
    entrypoint:
      - java
      - -Xmx512m
      - -jar
      - /opt/shumway/shumway.jar
      - --spring.datasource.url=jdbc:postgresql://shumway-db:5432/shumway
      - --spring.datasource.username=postgres
      - --spring.datasource.password=postgres
      - --management.metrics.export.statsd.enabled=false
    depends_on:
      shumway-db:
        condition: service_healthy
    healthcheck:
      test: "curl http://localhost:8023/actuator/health"
      interval: 5s
      timeout: 1s
      retries: 20

  party-management:
    image: ghcr.io/valitydev/party-management:sha-18bba50
    command: /opt/party-management/bin/party-management foreground
    depends_on:
      machinegun:
        condition: service_healthy
      dominant:
        condition: service_started
      shumway:
        condition: service_healthy
    healthcheck:
      test: "/opt/party-management/bin/party-management ping"
      interval: 10s
      timeout: 5s
      retries: 10

  bender:
    image: ghcr.io/valitydev/bender:sha-c9ea00f
    command: /opt/bender/bin/bender foreground
    depends_on:
      machinegun:
        condition: service_healthy
    healthcheck:
      test: "/opt/bender/bin/bender ping"
      interval: 10s
      timeout: 5s
      retries: 10

  shumway-db:
    image: docker.io/library/postgres:9.6
    environment:
      - POSTGRES_DB=shumway
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SERVICE_NAME=shumway-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
